version: '3.9'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    command: >
      python3 manage.py runserver 0.0.0.0:8000
